name: Deploy to Ubuntu server
trigger:
- master

pool:
  vmImage: self-hosted
  name: Ubuntu-Agent

steps:
- script: |
    CURR="$(pwd)"
    TRGT="/home/$USER"
    APP="$TRGT/vetrodilusso"

        echo 'Starting with the deployment process, '
        echo 'doing the initial steps... wait..'

    if [[ -d $APP && -e $APP ]]; then
        echo "Info:The $APP dir exists... This will be removed"
        rm -R $APP
        echo "Done!. $APP directory was removed successful"
        echo
    fi

    if [[ -e $TRGT && -w $TRGT ]]; then
        echo "Info:The app dir will be moved from $CURR to $APP"
        mv $CURR $APP 
        echo "Info:The app dir was moved from $CURR to $APP"
        cd $APP
        echo
      else
        echo "Info:The app dir will be copied from $CURR to $APP"
        cp -u -r $CURR $APP 
        echo "Info:The app dir was copied from $CURR to $APP"
        cd $APP
        echo
    fi

        chmod -R +wrx $APP

    if [[ $(pwd) != $APP ]]; then
        cd $APP 
    fi

        echo 'Success!. the last step finished with any issue... Performing the next step...'
        echo
        echo 'Starting compilation for development...'
        echo 'Wait.. This may take several minutes...'

    if [[ $(`npm install`) -eq "0" ]]; then
        echo 'Done!. The app was compiled. No further errors...'
        echo
        echo 'Info:. finishing the deployment. '
        echo 'This Webapp can be found in "http://${hostname}:3000" '
        exit 0
      else
        echo 'Error:. Oh! something is getting problems.. Please inspect the logs'
        echo 'and your project settings to find the issue(s) and try again';
        exit 1
    fi

  displayName: 'Initialize development mode'
